using System;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Protobuf.Generator.CodeTemplates;
using Protobuf.Parser;

namespace Protobuf.Generator;

/// <summary>
/// Protobuf Source Generator
/// </summary>
[Generator]
public sealed class ProtoSourceGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // 注册 .proto 文件作为额外文本
        context.RegisterForPostInitialization(ctx =>
        {
            ctx.AddSource("ProtoSourceGenerator.g.cs", @"
// This is an indicator file for the Protobuf Source Generator
namespace Protobuf.Generator
{
    internal static class GeneratorIndicator
    {
        public const string Version = ""1.0.0"";
    }
}
");
        });

        // 注册配置文件支持
        // context.RegisterForSyntaxNotifications(context => ...);
    }

    public void Execute(GeneratorExecutionContext context)
    {
        // 查找所有 .proto 文件
        var protoFiles = context.AdditionalFiles
            .Where(static file => file.Path != null && file.Path.EndsWith(".proto", StringComparison.OrdinalIgnoreCase))
            .ToArray();

        if (!protoFiles.Any())
        {
            return;
        }

        foreach (var protoFile in protoFiles)
        {
            try
            {
                var sourceText = protoFile.GetText(context.CancellationToken);
                if (sourceText == null)
                {
                    continue;
                }

                var protoContent = sourceText.ToString();
                var fileName = Path.GetFileNameWithoutExtension(protoFile.Path);

                // 解析 .proto 文件
                var lexer = new Lexer(protoContent);
                var tokens = lexer.Tokenize();

                var protoParser = new Protobuf.Parser.Parser(tokens);
                var protoFileAst = protoParser.Parse();

                // 设置文件路径
                protoFileAst.FilePath = protoFile.Path;

                // 生成代码
                GenerateCode(context, protoFileAst, fileName);
            }
            catch (Exception ex)
            {
                // 报告错误
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "PROTO001",
                            "Proto File Error",
                            $"Error processing proto file: {ex.Message}",
                            "Protobuf.Generator",
                            DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        Location.Create(protoFile.Path, TextSpan.FromBounds(0, 0), new LinePositionSpan(new LinePosition(0, 0), new LinePosition(0, 0)))));
            }
        }
    }

    private void GenerateCode(GeneratorExecutionContext context, ProtoFile protoFile, string fileName)
    {
        var codeBuilder = new System.Text.StringBuilder();

        // 生成文件头
        codeBuilder.AppendLine("// <auto-generated>");
        codeBuilder.AppendLine("//     Generated by Protobuf Source Generator");
        codeBuilder.AppendLine("// </auto-generated>");
        codeBuilder.AppendLine();
        codeBuilder.AppendLine("#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member");
        codeBuilder.AppendLine();

        // 确定命名空间
        var namespaceName = protoFile.Package;
        if (string.IsNullOrEmpty(namespaceName))
        {
            namespaceName = "Generated.Protobuf";
        }

        // 生成所有枚举
        foreach (var enumDecl in protoFile.Enums)
        {
            var enumTemplate = new EnumTemplate(enumDecl, namespaceName);
            codeBuilder.AppendLine(enumTemplate.Generate());
            codeBuilder.AppendLine();
        }

        // 生成所有消息
        foreach (var messageDecl in protoFile.Messages)
        {
            var messageTemplate = new MessageTemplate(messageDecl, namespaceName, protoFile);
            codeBuilder.AppendLine(messageTemplate.Generate());
            codeBuilder.AppendLine();
        }

        var code = codeBuilder.ToString();

        // 添加生成的代码
        var hintName = $"{fileName}.g.cs";
        context.AddSource(hintName, code);
    }
}
